name: Deploy to PS.kz via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host: 194.39.65.4
          ftp_username: dalidaml
          ftp_password: ${{ secrets.FTP_PASSWORD }}
          local_source_dir: "."
          dist_target_dir: "/vinopark.dalidam.live"
          delete: "false"
          exclude: '".git* .github Dockerfile nixpacks.toml test.php mail_log.php"'
