name: Deploy to PS.kz via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 194.39.65.4
          username: dalidaml
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /vinopark.dalidam.live/
          protocol: ftps
          port: 21
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            Dockerfile
            nixpacks.toml
            test.php
            mail_log.php
